---
title: "Price Prediction App"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
#Libraries
library(flexdashboard)

library(tidyverse)
library(tidyquant)

library(plotly)

library(parsnip)
library(xgboost)

library(odbc)
library(RSQLite)

#Data

con <- dbConnect(RSQLite::SQLite(), "../00_data/bikes_database.db")

#dbListTables(con)
bikes_tbl <- tbl(con, "bikes") %>% collect()

dbDisconnect(con)

#Scripts
source("../00_scripts/02_process_data.R")
source("../00_scripts/03_make_predictions.R")


#Models
model_xgboost <-  read_rds("../00_model/model_xgboost.rds")


```

Column {.sidebar}
-----------------------------------------------------------------------
App Inputs


Column {data-width=650}
-----------------------------------------------------------------------
```{r}
new_bike_tbl <- generate_new_bike(
  bike_model =  "Jekyll A1 1 Black Inc.",
  category_1 = "Mountain",
  category_2 = "Over Mountain",
  frame_material = "Aluminum",
  .ml_model = model_xgboost
)
```



### Price Prediction vs Product Portfolio

```{r}
bind_bike_prediction(bikes_tbl, new_bike_tbl) %>%
  plot_bike_prediction()
```

Column {data-width=350}
-----------------------------------------------------------------------

### Features used

```{r}
new_bike_tbl %>% format_table()
```

