---
title: "Analytics Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(shinyWidgets)

#core libraries
library(tidyverse)
library(tidyquant)
library(devtools)

#Interactive
library(plotly)
#install_version("plotly", version = "4.8.0", repos = "http://cran.us.r-project.org"
#Database
library(odbc)
library(RSQLite)
```

```{r message=TRUE, warning=TRUE, include=FALSE}
#Setup Connection to tables
con <- dbConnect(RSQLite::SQLite(), "../00_data/bikes_database.db")
#con <- dbConnect(RSQLite::SQLite(), "00_data/bikes_database.db")
bikes_tbl <- tbl(con, "bikes")
bikeshops_tbl <- tbl(con, "bikeshops")
orderlines_tbl <- tbl(con, "orderlines")

#Joining Data
processed_data_tbl <- orderlines_tbl %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id")) %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  mutate(extended_price = quantity * price) %>%
  collect()
  
processed_data_tbl <- processed_data_tbl %>%
  mutate(order.date = ymd(order.date)) %>%
  separate(location, into = c("city", "state"), sep = ", ") %>%
  separate(description, 
           into = c("category_1", "category_2", "frame_material"),
           sep = " - ") %>%
  select(order.date, order.id, order.line, state, quantity, price, extended_price, category_1:frame_material)
  
#DB Connection Close
dbDisconnect(con)
```

Column {.sidebar}
----------------------------------------------

```{r}
dateRangeInput(inputId = "date_range",
               label = h4("Date Range"),
               start = min(processed_data_tbl$order.date),
               end = today(),
               min = min(processed_data_tbl$order.date),
               max = today(),
               startview = "year")


shinyWidgets::checkboxGroupButtons(inputId = "checkbox_category_1",
                                   label = h4("Bike Type"),
                                   choices = unique(processed_data_tbl$category_1),
                                   selected = unique(processed_data_tbl$category_1),
                                   checkIcon = list(
                                     yes = icon("ok", lib = "glyphicon"),
                                     no = icon("remove", lib = "glyphicon")
                                   ))


shinyWidgets::pickerInput(inputId = "picker_category_2",
                          label = h4("Bike Family"),
                          choices = unique(processed_data_tbl$category_2),
                          selected = unique(processed_data_tbl$category_2),
                          multiple = TRUE,
                          options = list(
                            `actions-box` = TRUE,
                            size = 10,
                            `selected-text-format` = "count > 3"
                          ))

br()
hr()

actionButton(inputId = "reset", label = "Reset", icon = icon("sync"))

observeEvent(eventExpr = input$reset, handlerExpr = {
  
  updateCheckboxGroupButtons(
    session = session,
    inputId = "checkbox_category_1",
    selected = unique(processed_data_tbl$category_1)
  )
  updatePickerInput(
    session = session,
    inputId = "picker_category_2",
    selected = unique(processed_data_tbl$category_2)
  )
  updateDateRangeInput(
    session = session,
    inputId = "date_range",
    start = min(processed_data_tbl$order.date),
    end = today()
  )
})

```



Column {data-width=1000}
----------------------------------------------

### By State

```{r}

geo_plot_tbl <- reactive({
  
  processed_data_tbl %>%
    
    filter(category_1 %in% input$checkbox_category_1) %>%
    
    filter(category_2 %in% input$picker_category_2) %>%
    
    filter(order.date %>% between(left = ymd(input$date_range[1]),
                                  right = ymd(input$date_range[2]))) %>%
  
    group_by(state) %>%
    summarise(totalrevenue = sum(extended_price)) %>%
    ungroup() %>%
    mutate(label_text = str_glue("State: {state}
                               Revenue: {scales::dollar(totalrevenue)}"))
})


```


```{r}

output$plotly_1 <- renderPlotly(expr = {
  geo_plot_tbl() %>% 
  plot_geo(locationmode = "USA-states") %>%
  add_trace(z = ~totalrevenue, 
            locations = ~state, 
            color = ~totalrevenue,
            text = ~label_text,
            colors = "Blues") %>%
  layout(
    geo = list(
      scope = "usa",
      projection = list(type = "albers usa"),
      showlakes = TRUE,
      lakecolor = toRGB("white")
    )
  )
})

plotlyOutput(outputId = "plotly_1")

```










